application: phish-shell
version: 1
runtime: php
api_version: 1

handlers:
- url: /static
  static_dir: static
  expiration: 30d

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 30d

- url: /shell.do
  script: front/shell.php

- url: /reset.do
  script: front/reset.php

- url: .*
  script: front/frontpage.php
